---
- name: Play for creating project development environment
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

  roles:
    - python
    - pipx
    - pyscaffold
    - tox
